name: example
description: math_view example app
publish_to: none

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  math_view:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
