// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1763471870;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__editor_api__close_editor_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "close_editor",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::editor_api::close_editor(api_id);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__editor_api__create_editor_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_editor",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::editor_api::create_editor())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__editor_api__create_editor_from_latex_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_editor_from_latex",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_latex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(
                    crate::api::editor_api::create_editor_from_latex(api_latex),
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__editor_api__dispatch_editor_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "dispatch_editor",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <String>::sse_decode(&mut deserializer);
            let api_intent = <crate::api::editor_api::EditorIntent>::sse_decode(&mut deserializer);
            let api_display_mode = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::editor_api::dispatch_editor(
                    api_id,
                    api_intent,
                    api_display_mode,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__editor_api__get_editor_snapshot_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_editor_snapshot",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <String>::sse_decode(&mut deserializer);
            let api_display_mode = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::editor_api::get_editor_snapshot(
                    api_id,
                    api_display_mode,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__editor_api__get_selected_latex_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_selected_latex",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::editor_api::get_selected_latex(api_id))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__math_api__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::math_api::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__math_api__layout_math_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "layout_math",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_latex = <String>::sse_decode(&mut deserializer);
            let api_display_mode = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::math_api::layout_math(
                    api_latex,
                    api_display_mode,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__math_api__layout_math_tree_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "layout_math_tree",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_latex = <String>::sse_decode(&mut deserializer);
            let api_display_mode = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::math_api::layout_math_tree(
                    api_latex,
                    api_display_mode,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::editor_layout::BlockLayout {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_blockId = <u32>::sse_decode(deserializer);
        let mut var_width = <f64>::sse_decode(deserializer);
        let mut var_height = <f64>::sse_decode(deserializer);
        let mut var_depth = <f64>::sse_decode(deserializer);
        let mut var_caretPositions = <Vec<f64>>::sse_decode(deserializer);
        let mut var_baselineShift = <f64>::sse_decode(deserializer);
        let mut var_fontScale = <f64>::sse_decode(deserializer);
        let mut var_leftX = <f64>::sse_decode(deserializer);
        let mut var_children =
            <Vec<crate::api::editor_layout::NodeLayout>>::sse_decode(deserializer);
        let mut var_cursorIndex = <Option<u32>>::sse_decode(deserializer);
        let mut var_selection =
            <Option<crate::api::editor_layout::BlockSelection>>::sse_decode(deserializer);
        let mut var_isEmpty = <bool>::sse_decode(deserializer);
        return crate::api::editor_layout::BlockLayout {
            block_id: var_blockId,
            width: var_width,
            height: var_height,
            depth: var_depth,
            caret_positions: var_caretPositions,
            baseline_shift: var_baselineShift,
            font_scale: var_fontScale,
            left_x: var_leftX,
            children: var_children,
            cursor_index: var_cursorIndex,
            selection: var_selection,
            is_empty: var_isEmpty,
        };
    }
}

impl SseDecode for crate::api::editor_layout::BlockSelection {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_start = <u32>::sse_decode(deserializer);
        let mut var_end = <u32>::sse_decode(deserializer);
        return crate::api::editor_layout::BlockSelection {
            start: var_start,
            end: var_end,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::editor_layout::CommandLayoutKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::editor_layout::CommandLayoutKind::Frac;
            }
            1 => {
                return crate::api::editor_layout::CommandLayoutKind::Sqrt;
            }
            2 => {
                return crate::api::editor_layout::CommandLayoutKind::NthRoot;
            }
            3 => {
                return crate::api::editor_layout::CommandLayoutKind::Sup;
            }
            4 => {
                return crate::api::editor_layout::CommandLayoutKind::Sub;
            }
            5 => {
                return crate::api::editor_layout::CommandLayoutKind::SupSub;
            }
            6 => {
                return crate::api::editor_layout::CommandLayoutKind::Overline;
            }
            7 => {
                return crate::api::editor_layout::CommandLayoutKind::Underline;
            }
            8 => {
                return crate::api::editor_layout::CommandLayoutKind::LeftRight;
            }
            9 => {
                return crate::api::editor_layout::CommandLayoutKind::SumLike;
            }
            10 => {
                let mut var_rows = <u32>::sse_decode(deserializer);
                let mut var_cols = <u32>::sse_decode(deserializer);
                return crate::api::editor_layout::CommandLayoutKind::Matrix {
                    rows: var_rows,
                    cols: var_cols,
                };
            }
            11 => {
                return crate::api::editor_layout::CommandLayoutKind::Text;
            }
            12 => {
                let mut var_text = <String>::sse_decode(deserializer);
                return crate::api::editor_layout::CommandLayoutKind::LatexCommandInput {
                    text: var_text,
                };
            }
            13 => {
                return crate::api::editor_layout::CommandLayoutKind::Other;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::editor_api::EditorIntent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_ch = <String>::sse_decode(deserializer);
                return crate::api::editor_api::EditorIntent::InsertSymbol { ch: var_ch };
            }
            1 => {
                return crate::api::editor_api::EditorIntent::InsertFrac;
            }
            2 => {
                return crate::api::editor_api::EditorIntent::LiveFraction;
            }
            3 => {
                return crate::api::editor_api::EditorIntent::InsertSqrt;
            }
            4 => {
                return crate::api::editor_api::EditorIntent::InsertNthRoot;
            }
            5 => {
                return crate::api::editor_api::EditorIntent::InsertSup;
            }
            6 => {
                return crate::api::editor_api::EditorIntent::InsertSub;
            }
            7 => {
                return crate::api::editor_api::EditorIntent::InsertParentheses;
            }
            8 => {
                return crate::api::editor_api::EditorIntent::InsertBrackets;
            }
            9 => {
                return crate::api::editor_api::EditorIntent::InsertBraces;
            }
            10 => {
                return crate::api::editor_api::EditorIntent::InsertAbs;
            }
            11 => {
                return crate::api::editor_api::EditorIntent::InsertSum;
            }
            12 => {
                return crate::api::editor_api::EditorIntent::InsertProduct;
            }
            13 => {
                return crate::api::editor_api::EditorIntent::InsertIntegral;
            }
            14 => {
                return crate::api::editor_api::EditorIntent::InsertLimit;
            }
            15 => {
                return crate::api::editor_api::EditorIntent::InsertOverline;
            }
            16 => {
                return crate::api::editor_api::EditorIntent::InsertUnderline;
            }
            17 => {
                return crate::api::editor_api::EditorIntent::InsertText;
            }
            18 => {
                return crate::api::editor_api::EditorIntent::InsertCommandInput;
            }
            19 => {
                let mut var_ch = <String>::sse_decode(deserializer);
                return crate::api::editor_api::EditorIntent::CommandInputType { ch: var_ch };
            }
            20 => {
                return crate::api::editor_api::EditorIntent::CommandInputBackspace;
            }
            21 => {
                return crate::api::editor_api::EditorIntent::ResolveCommandInput;
            }
            22 => {
                return crate::api::editor_api::EditorIntent::CancelCommandInput;
            }
            23 => {
                return crate::api::editor_api::EditorIntent::MoveLeft;
            }
            24 => {
                return crate::api::editor_api::EditorIntent::MoveRight;
            }
            25 => {
                return crate::api::editor_api::EditorIntent::EscapeRight;
            }
            26 => {
                return crate::api::editor_api::EditorIntent::MoveUp;
            }
            27 => {
                return crate::api::editor_api::EditorIntent::MoveDown;
            }
            28 => {
                return crate::api::editor_api::EditorIntent::MoveToStart;
            }
            29 => {
                return crate::api::editor_api::EditorIntent::MoveToEnd;
            }
            30 => {
                return crate::api::editor_api::EditorIntent::SelectLeft;
            }
            31 => {
                return crate::api::editor_api::EditorIntent::SelectRight;
            }
            32 => {
                return crate::api::editor_api::EditorIntent::SelectAll;
            }
            33 => {
                return crate::api::editor_api::EditorIntent::DeleteBackward;
            }
            34 => {
                return crate::api::editor_api::EditorIntent::DeleteForward;
            }
            35 => {
                let mut var_latex = <String>::sse_decode(deserializer);
                return crate::api::editor_api::EditorIntent::SetLatex { latex: var_latex };
            }
            36 => {
                let mut var_latex = <String>::sse_decode(deserializer);
                return crate::api::editor_api::EditorIntent::InsertLatex { latex: var_latex };
            }
            37 => {
                let mut var_blockId = <u32>::sse_decode(deserializer);
                let mut var_caretIndex = <u32>::sse_decode(deserializer);
                return crate::api::editor_api::EditorIntent::TapBlock {
                    block_id: var_blockId,
                    caret_index: var_caretIndex,
                };
            }
            38 => {
                let mut var_blockId = <u32>::sse_decode(deserializer);
                let mut var_caretIndex = <u32>::sse_decode(deserializer);
                return crate::api::editor_api::EditorIntent::DragStart {
                    block_id: var_blockId,
                    caret_index: var_caretIndex,
                };
            }
            39 => {
                let mut var_blockId = <u32>::sse_decode(deserializer);
                let mut var_caretIndex = <u32>::sse_decode(deserializer);
                return crate::api::editor_api::EditorIntent::DragUpdate {
                    block_id: var_blockId,
                    caret_index: var_caretIndex,
                };
            }
            40 => {
                return crate::api::editor_api::EditorIntent::Undo;
            }
            41 => {
                return crate::api::editor_api::EditorIntent::Redo;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::editor_layout::EditorLayout {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_root = <crate::api::editor_layout::BlockLayout>::sse_decode(deserializer);
        let mut var_untagged = <Vec<crate::api::math_api::MathNode>>::sse_decode(deserializer);
        return crate::api::editor_layout::EditorLayout {
            root: var_root,
            untagged: var_untagged,
        };
    }
}

impl SseDecode for crate::api::editor_api::EditorSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_editorLayout =
            <crate::api::editor_layout::EditorLayout>::sse_decode(deserializer);
        let mut var_latex = <String>::sse_decode(deserializer);
        let mut var_inCommandInput = <bool>::sse_decode(deserializer);
        return crate::api::editor_api::EditorSnapshot {
            editor_layout: var_editorLayout,
            latex: var_latex,
            in_command_input: var_inCommandInput,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::editor_layout::BlockLayout> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::editor_layout::BlockLayout>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::math_api::MathNode> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::math_api::MathNode>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::editor_layout::NodeLayout> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::editor_layout::NodeLayout>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::math_api::PathCommand> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::math_api::PathCommand>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<f64>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::math_api::MathLayout {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_width = <f64>::sse_decode(deserializer);
        let mut var_height = <f64>::sse_decode(deserializer);
        let mut var_depth = <f64>::sse_decode(deserializer);
        let mut var_nodes = <Vec<crate::api::math_api::MathNode>>::sse_decode(deserializer);
        return crate::api::math_api::MathLayout {
            width: var_width,
            height: var_height,
            depth: var_depth,
            nodes: var_nodes,
        };
    }
}

impl SseDecode for crate::api::math_api::MathNode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_codepoint = <u32>::sse_decode(deserializer);
                let mut var_x = <f64>::sse_decode(deserializer);
                let mut var_y = <f64>::sse_decode(deserializer);
                let mut var_fontName = <String>::sse_decode(deserializer);
                let mut var_scale = <f64>::sse_decode(deserializer);
                let mut var_width = <f64>::sse_decode(deserializer);
                let mut var_color = <Option<String>>::sse_decode(deserializer);
                let mut var_nodeId = <Option<u32>>::sse_decode(deserializer);
                return crate::api::math_api::MathNode::Glyph {
                    codepoint: var_codepoint,
                    x: var_x,
                    y: var_y,
                    font_name: var_fontName,
                    scale: var_scale,
                    width: var_width,
                    color: var_color,
                    node_id: var_nodeId,
                };
            }
            1 => {
                let mut var_x = <f64>::sse_decode(deserializer);
                let mut var_y = <f64>::sse_decode(deserializer);
                let mut var_width = <f64>::sse_decode(deserializer);
                let mut var_height = <f64>::sse_decode(deserializer);
                let mut var_color = <Option<String>>::sse_decode(deserializer);
                let mut var_nodeId = <Option<u32>>::sse_decode(deserializer);
                return crate::api::math_api::MathNode::Rule {
                    x: var_x,
                    y: var_y,
                    width: var_width,
                    height: var_height,
                    color: var_color,
                    node_id: var_nodeId,
                };
            }
            2 => {
                let mut var_x = <f64>::sse_decode(deserializer);
                let mut var_y = <f64>::sse_decode(deserializer);
                let mut var_width = <f64>::sse_decode(deserializer);
                let mut var_height = <f64>::sse_decode(deserializer);
                let mut var_viewBoxX = <f64>::sse_decode(deserializer);
                let mut var_viewBoxY = <f64>::sse_decode(deserializer);
                let mut var_viewBoxWidth = <f64>::sse_decode(deserializer);
                let mut var_viewBoxHeight = <f64>::sse_decode(deserializer);
                let mut var_commands =
                    <Vec<crate::api::math_api::PathCommand>>::sse_decode(deserializer);
                let mut var_nodeId = <Option<u32>>::sse_decode(deserializer);
                return crate::api::math_api::MathNode::SvgPath {
                    x: var_x,
                    y: var_y,
                    width: var_width,
                    height: var_height,
                    view_box_x: var_viewBoxX,
                    view_box_y: var_viewBoxY,
                    view_box_width: var_viewBoxWidth,
                    view_box_height: var_viewBoxHeight,
                    commands: var_commands,
                    node_id: var_nodeId,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::editor_layout::NodeLayout {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_nodeId = <u32>::sse_decode(deserializer);
                let mut var_glyphs =
                    <Vec<crate::api::math_api::MathNode>>::sse_decode(deserializer);
                let mut var_width = <f64>::sse_decode(deserializer);
                let mut var_height = <f64>::sse_decode(deserializer);
                let mut var_depth = <f64>::sse_decode(deserializer);
                let mut var_leftX = <f64>::sse_decode(deserializer);
                return crate::api::editor_layout::NodeLayout::Leaf {
                    node_id: var_nodeId,
                    glyphs: var_glyphs,
                    width: var_width,
                    height: var_height,
                    depth: var_depth,
                    left_x: var_leftX,
                };
            }
            1 => {
                let mut var_nodeId = <u32>::sse_decode(deserializer);
                let mut var_kind =
                    <crate::api::editor_layout::CommandLayoutKind>::sse_decode(deserializer);
                let mut var_width = <f64>::sse_decode(deserializer);
                let mut var_height = <f64>::sse_decode(deserializer);
                let mut var_depth = <f64>::sse_decode(deserializer);
                let mut var_leftX = <f64>::sse_decode(deserializer);
                let mut var_childBlocks =
                    <Vec<crate::api::editor_layout::BlockLayout>>::sse_decode(deserializer);
                let mut var_decorations =
                    <Vec<crate::api::math_api::MathNode>>::sse_decode(deserializer);
                return crate::api::editor_layout::NodeLayout::Command {
                    node_id: var_nodeId,
                    kind: var_kind,
                    width: var_width,
                    height: var_height,
                    depth: var_depth,
                    left_x: var_leftX,
                    child_blocks: var_childBlocks,
                    decorations: var_decorations,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::editor_layout::BlockSelection> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::editor_layout::BlockSelection>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::math_api::PathCommand {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_x = <f64>::sse_decode(deserializer);
                let mut var_y = <f64>::sse_decode(deserializer);
                return crate::api::math_api::PathCommand::MoveTo { x: var_x, y: var_y };
            }
            1 => {
                let mut var_x = <f64>::sse_decode(deserializer);
                let mut var_y = <f64>::sse_decode(deserializer);
                return crate::api::math_api::PathCommand::LineTo { x: var_x, y: var_y };
            }
            2 => {
                let mut var_x1 = <f64>::sse_decode(deserializer);
                let mut var_y1 = <f64>::sse_decode(deserializer);
                let mut var_x2 = <f64>::sse_decode(deserializer);
                let mut var_y2 = <f64>::sse_decode(deserializer);
                let mut var_x = <f64>::sse_decode(deserializer);
                let mut var_y = <f64>::sse_decode(deserializer);
                return crate::api::math_api::PathCommand::CubicTo {
                    x1: var_x1,
                    y1: var_y1,
                    x2: var_x2,
                    y2: var_y2,
                    x: var_x,
                    y: var_y,
                };
            }
            3 => {
                let mut var_x1 = <f64>::sse_decode(deserializer);
                let mut var_y1 = <f64>::sse_decode(deserializer);
                let mut var_x = <f64>::sse_decode(deserializer);
                let mut var_y = <f64>::sse_decode(deserializer);
                return crate::api::math_api::PathCommand::QuadTo {
                    x1: var_x1,
                    y1: var_y1,
                    x: var_x,
                    y: var_y,
                };
            }
            4 => {
                return crate::api::math_api::PathCommand::Close;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        7 => wire__crate__api__math_api__init_app_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__editor_api__close_editor_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__editor_api__create_editor_impl(ptr, rust_vec_len, data_len),
        3 => {
            wire__crate__api__editor_api__create_editor_from_latex_impl(ptr, rust_vec_len, data_len)
        }
        4 => wire__crate__api__editor_api__dispatch_editor_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__editor_api__get_editor_snapshot_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__editor_api__get_selected_latex_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__math_api__layout_math_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__math_api__layout_math_tree_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::editor_layout::BlockLayout {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.block_id.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.depth.into_into_dart().into_dart(),
            self.caret_positions.into_into_dart().into_dart(),
            self.baseline_shift.into_into_dart().into_dart(),
            self.font_scale.into_into_dart().into_dart(),
            self.left_x.into_into_dart().into_dart(),
            self.children.into_into_dart().into_dart(),
            self.cursor_index.into_into_dart().into_dart(),
            self.selection.into_into_dart().into_dart(),
            self.is_empty.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::editor_layout::BlockLayout
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::editor_layout::BlockLayout>
    for crate::api::editor_layout::BlockLayout
{
    fn into_into_dart(self) -> crate::api::editor_layout::BlockLayout {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::editor_layout::BlockSelection {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.start.into_into_dart().into_dart(),
            self.end.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::editor_layout::BlockSelection
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::editor_layout::BlockSelection>
    for crate::api::editor_layout::BlockSelection
{
    fn into_into_dart(self) -> crate::api::editor_layout::BlockSelection {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::editor_layout::CommandLayoutKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::editor_layout::CommandLayoutKind::Frac => [0.into_dart()].into_dart(),
            crate::api::editor_layout::CommandLayoutKind::Sqrt => [1.into_dart()].into_dart(),
            crate::api::editor_layout::CommandLayoutKind::NthRoot => [2.into_dart()].into_dart(),
            crate::api::editor_layout::CommandLayoutKind::Sup => [3.into_dart()].into_dart(),
            crate::api::editor_layout::CommandLayoutKind::Sub => [4.into_dart()].into_dart(),
            crate::api::editor_layout::CommandLayoutKind::SupSub => [5.into_dart()].into_dart(),
            crate::api::editor_layout::CommandLayoutKind::Overline => [6.into_dart()].into_dart(),
            crate::api::editor_layout::CommandLayoutKind::Underline => [7.into_dart()].into_dart(),
            crate::api::editor_layout::CommandLayoutKind::LeftRight => [8.into_dart()].into_dart(),
            crate::api::editor_layout::CommandLayoutKind::SumLike => [9.into_dart()].into_dart(),
            crate::api::editor_layout::CommandLayoutKind::Matrix { rows, cols } => [
                10.into_dart(),
                rows.into_into_dart().into_dart(),
                cols.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::editor_layout::CommandLayoutKind::Text => [11.into_dart()].into_dart(),
            crate::api::editor_layout::CommandLayoutKind::LatexCommandInput { text } => {
                [12.into_dart(), text.into_into_dart().into_dart()].into_dart()
            }
            crate::api::editor_layout::CommandLayoutKind::Other => [13.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::editor_layout::CommandLayoutKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::editor_layout::CommandLayoutKind>
    for crate::api::editor_layout::CommandLayoutKind
{
    fn into_into_dart(self) -> crate::api::editor_layout::CommandLayoutKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::editor_api::EditorIntent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::editor_api::EditorIntent::InsertSymbol { ch } => {
                [0.into_dart(), ch.into_into_dart().into_dart()].into_dart()
            }
            crate::api::editor_api::EditorIntent::InsertFrac => [1.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::LiveFraction => [2.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertSqrt => [3.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertNthRoot => [4.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertSup => [5.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertSub => [6.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertParentheses => [7.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertBrackets => [8.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertBraces => [9.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertAbs => [10.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertSum => [11.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertProduct => [12.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertIntegral => [13.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertLimit => [14.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertOverline => [15.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertUnderline => [16.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertText => [17.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::InsertCommandInput => {
                [18.into_dart()].into_dart()
            }
            crate::api::editor_api::EditorIntent::CommandInputType { ch } => {
                [19.into_dart(), ch.into_into_dart().into_dart()].into_dart()
            }
            crate::api::editor_api::EditorIntent::CommandInputBackspace => {
                [20.into_dart()].into_dart()
            }
            crate::api::editor_api::EditorIntent::ResolveCommandInput => {
                [21.into_dart()].into_dart()
            }
            crate::api::editor_api::EditorIntent::CancelCommandInput => {
                [22.into_dart()].into_dart()
            }
            crate::api::editor_api::EditorIntent::MoveLeft => [23.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::MoveRight => [24.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::EscapeRight => [25.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::MoveUp => [26.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::MoveDown => [27.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::MoveToStart => [28.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::MoveToEnd => [29.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::SelectLeft => [30.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::SelectRight => [31.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::SelectAll => [32.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::DeleteBackward => [33.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::DeleteForward => [34.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::SetLatex { latex } => {
                [35.into_dart(), latex.into_into_dart().into_dart()].into_dart()
            }
            crate::api::editor_api::EditorIntent::InsertLatex { latex } => {
                [36.into_dart(), latex.into_into_dart().into_dart()].into_dart()
            }
            crate::api::editor_api::EditorIntent::TapBlock {
                block_id,
                caret_index,
            } => [
                37.into_dart(),
                block_id.into_into_dart().into_dart(),
                caret_index.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::editor_api::EditorIntent::DragStart {
                block_id,
                caret_index,
            } => [
                38.into_dart(),
                block_id.into_into_dart().into_dart(),
                caret_index.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::editor_api::EditorIntent::DragUpdate {
                block_id,
                caret_index,
            } => [
                39.into_dart(),
                block_id.into_into_dart().into_dart(),
                caret_index.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::editor_api::EditorIntent::Undo => [40.into_dart()].into_dart(),
            crate::api::editor_api::EditorIntent::Redo => [41.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::editor_api::EditorIntent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::editor_api::EditorIntent>
    for crate::api::editor_api::EditorIntent
{
    fn into_into_dart(self) -> crate::api::editor_api::EditorIntent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::editor_layout::EditorLayout {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.root.into_into_dart().into_dart(),
            self.untagged.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::editor_layout::EditorLayout
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::editor_layout::EditorLayout>
    for crate::api::editor_layout::EditorLayout
{
    fn into_into_dart(self) -> crate::api::editor_layout::EditorLayout {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::editor_api::EditorSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.editor_layout.into_into_dart().into_dart(),
            self.latex.into_into_dart().into_dart(),
            self.in_command_input.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::editor_api::EditorSnapshot
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::editor_api::EditorSnapshot>
    for crate::api::editor_api::EditorSnapshot
{
    fn into_into_dart(self) -> crate::api::editor_api::EditorSnapshot {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::math_api::MathLayout {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.depth.into_into_dart().into_dart(),
            self.nodes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::math_api::MathLayout
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::math_api::MathLayout>
    for crate::api::math_api::MathLayout
{
    fn into_into_dart(self) -> crate::api::math_api::MathLayout {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::math_api::MathNode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::math_api::MathNode::Glyph {
                codepoint,
                x,
                y,
                font_name,
                scale,
                width,
                color,
                node_id,
            } => [
                0.into_dart(),
                codepoint.into_into_dart().into_dart(),
                x.into_into_dart().into_dart(),
                y.into_into_dart().into_dart(),
                font_name.into_into_dart().into_dart(),
                scale.into_into_dart().into_dart(),
                width.into_into_dart().into_dart(),
                color.into_into_dart().into_dart(),
                node_id.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::math_api::MathNode::Rule {
                x,
                y,
                width,
                height,
                color,
                node_id,
            } => [
                1.into_dart(),
                x.into_into_dart().into_dart(),
                y.into_into_dart().into_dart(),
                width.into_into_dart().into_dart(),
                height.into_into_dart().into_dart(),
                color.into_into_dart().into_dart(),
                node_id.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::math_api::MathNode::SvgPath {
                x,
                y,
                width,
                height,
                view_box_x,
                view_box_y,
                view_box_width,
                view_box_height,
                commands,
                node_id,
            } => [
                2.into_dart(),
                x.into_into_dart().into_dart(),
                y.into_into_dart().into_dart(),
                width.into_into_dart().into_dart(),
                height.into_into_dart().into_dart(),
                view_box_x.into_into_dart().into_dart(),
                view_box_y.into_into_dart().into_dart(),
                view_box_width.into_into_dart().into_dart(),
                view_box_height.into_into_dart().into_dart(),
                commands.into_into_dart().into_dart(),
                node_id.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::math_api::MathNode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::math_api::MathNode>
    for crate::api::math_api::MathNode
{
    fn into_into_dart(self) -> crate::api::math_api::MathNode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::editor_layout::NodeLayout {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::editor_layout::NodeLayout::Leaf {
                node_id,
                glyphs,
                width,
                height,
                depth,
                left_x,
            } => [
                0.into_dart(),
                node_id.into_into_dart().into_dart(),
                glyphs.into_into_dart().into_dart(),
                width.into_into_dart().into_dart(),
                height.into_into_dart().into_dart(),
                depth.into_into_dart().into_dart(),
                left_x.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::editor_layout::NodeLayout::Command {
                node_id,
                kind,
                width,
                height,
                depth,
                left_x,
                child_blocks,
                decorations,
            } => [
                1.into_dart(),
                node_id.into_into_dart().into_dart(),
                kind.into_into_dart().into_dart(),
                width.into_into_dart().into_dart(),
                height.into_into_dart().into_dart(),
                depth.into_into_dart().into_dart(),
                left_x.into_into_dart().into_dart(),
                child_blocks.into_into_dart().into_dart(),
                decorations.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::editor_layout::NodeLayout
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::editor_layout::NodeLayout>
    for crate::api::editor_layout::NodeLayout
{
    fn into_into_dart(self) -> crate::api::editor_layout::NodeLayout {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::math_api::PathCommand {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::math_api::PathCommand::MoveTo { x, y } => [
                0.into_dart(),
                x.into_into_dart().into_dart(),
                y.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::math_api::PathCommand::LineTo { x, y } => [
                1.into_dart(),
                x.into_into_dart().into_dart(),
                y.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::math_api::PathCommand::CubicTo {
                x1,
                y1,
                x2,
                y2,
                x,
                y,
            } => [
                2.into_dart(),
                x1.into_into_dart().into_dart(),
                y1.into_into_dart().into_dart(),
                x2.into_into_dart().into_dart(),
                y2.into_into_dart().into_dart(),
                x.into_into_dart().into_dart(),
                y.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::math_api::PathCommand::QuadTo { x1, y1, x, y } => [
                3.into_dart(),
                x1.into_into_dart().into_dart(),
                y1.into_into_dart().into_dart(),
                x.into_into_dart().into_dart(),
                y.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::math_api::PathCommand::Close => [4.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::math_api::PathCommand
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::math_api::PathCommand>
    for crate::api::math_api::PathCommand
{
    fn into_into_dart(self) -> crate::api::math_api::PathCommand {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::editor_layout::BlockLayout {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.block_id, serializer);
        <f64>::sse_encode(self.width, serializer);
        <f64>::sse_encode(self.height, serializer);
        <f64>::sse_encode(self.depth, serializer);
        <Vec<f64>>::sse_encode(self.caret_positions, serializer);
        <f64>::sse_encode(self.baseline_shift, serializer);
        <f64>::sse_encode(self.font_scale, serializer);
        <f64>::sse_encode(self.left_x, serializer);
        <Vec<crate::api::editor_layout::NodeLayout>>::sse_encode(self.children, serializer);
        <Option<u32>>::sse_encode(self.cursor_index, serializer);
        <Option<crate::api::editor_layout::BlockSelection>>::sse_encode(self.selection, serializer);
        <bool>::sse_encode(self.is_empty, serializer);
    }
}

impl SseEncode for crate::api::editor_layout::BlockSelection {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.start, serializer);
        <u32>::sse_encode(self.end, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::editor_layout::CommandLayoutKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::editor_layout::CommandLayoutKind::Frac => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::editor_layout::CommandLayoutKind::Sqrt => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::editor_layout::CommandLayoutKind::NthRoot => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::editor_layout::CommandLayoutKind::Sup => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::editor_layout::CommandLayoutKind::Sub => {
                <i32>::sse_encode(4, serializer);
            }
            crate::api::editor_layout::CommandLayoutKind::SupSub => {
                <i32>::sse_encode(5, serializer);
            }
            crate::api::editor_layout::CommandLayoutKind::Overline => {
                <i32>::sse_encode(6, serializer);
            }
            crate::api::editor_layout::CommandLayoutKind::Underline => {
                <i32>::sse_encode(7, serializer);
            }
            crate::api::editor_layout::CommandLayoutKind::LeftRight => {
                <i32>::sse_encode(8, serializer);
            }
            crate::api::editor_layout::CommandLayoutKind::SumLike => {
                <i32>::sse_encode(9, serializer);
            }
            crate::api::editor_layout::CommandLayoutKind::Matrix { rows, cols } => {
                <i32>::sse_encode(10, serializer);
                <u32>::sse_encode(rows, serializer);
                <u32>::sse_encode(cols, serializer);
            }
            crate::api::editor_layout::CommandLayoutKind::Text => {
                <i32>::sse_encode(11, serializer);
            }
            crate::api::editor_layout::CommandLayoutKind::LatexCommandInput { text } => {
                <i32>::sse_encode(12, serializer);
                <String>::sse_encode(text, serializer);
            }
            crate::api::editor_layout::CommandLayoutKind::Other => {
                <i32>::sse_encode(13, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::editor_api::EditorIntent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::editor_api::EditorIntent::InsertSymbol { ch } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(ch, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertFrac => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::editor_api::EditorIntent::LiveFraction => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertSqrt => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertNthRoot => {
                <i32>::sse_encode(4, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertSup => {
                <i32>::sse_encode(5, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertSub => {
                <i32>::sse_encode(6, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertParentheses => {
                <i32>::sse_encode(7, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertBrackets => {
                <i32>::sse_encode(8, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertBraces => {
                <i32>::sse_encode(9, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertAbs => {
                <i32>::sse_encode(10, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertSum => {
                <i32>::sse_encode(11, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertProduct => {
                <i32>::sse_encode(12, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertIntegral => {
                <i32>::sse_encode(13, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertLimit => {
                <i32>::sse_encode(14, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertOverline => {
                <i32>::sse_encode(15, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertUnderline => {
                <i32>::sse_encode(16, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertText => {
                <i32>::sse_encode(17, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertCommandInput => {
                <i32>::sse_encode(18, serializer);
            }
            crate::api::editor_api::EditorIntent::CommandInputType { ch } => {
                <i32>::sse_encode(19, serializer);
                <String>::sse_encode(ch, serializer);
            }
            crate::api::editor_api::EditorIntent::CommandInputBackspace => {
                <i32>::sse_encode(20, serializer);
            }
            crate::api::editor_api::EditorIntent::ResolveCommandInput => {
                <i32>::sse_encode(21, serializer);
            }
            crate::api::editor_api::EditorIntent::CancelCommandInput => {
                <i32>::sse_encode(22, serializer);
            }
            crate::api::editor_api::EditorIntent::MoveLeft => {
                <i32>::sse_encode(23, serializer);
            }
            crate::api::editor_api::EditorIntent::MoveRight => {
                <i32>::sse_encode(24, serializer);
            }
            crate::api::editor_api::EditorIntent::EscapeRight => {
                <i32>::sse_encode(25, serializer);
            }
            crate::api::editor_api::EditorIntent::MoveUp => {
                <i32>::sse_encode(26, serializer);
            }
            crate::api::editor_api::EditorIntent::MoveDown => {
                <i32>::sse_encode(27, serializer);
            }
            crate::api::editor_api::EditorIntent::MoveToStart => {
                <i32>::sse_encode(28, serializer);
            }
            crate::api::editor_api::EditorIntent::MoveToEnd => {
                <i32>::sse_encode(29, serializer);
            }
            crate::api::editor_api::EditorIntent::SelectLeft => {
                <i32>::sse_encode(30, serializer);
            }
            crate::api::editor_api::EditorIntent::SelectRight => {
                <i32>::sse_encode(31, serializer);
            }
            crate::api::editor_api::EditorIntent::SelectAll => {
                <i32>::sse_encode(32, serializer);
            }
            crate::api::editor_api::EditorIntent::DeleteBackward => {
                <i32>::sse_encode(33, serializer);
            }
            crate::api::editor_api::EditorIntent::DeleteForward => {
                <i32>::sse_encode(34, serializer);
            }
            crate::api::editor_api::EditorIntent::SetLatex { latex } => {
                <i32>::sse_encode(35, serializer);
                <String>::sse_encode(latex, serializer);
            }
            crate::api::editor_api::EditorIntent::InsertLatex { latex } => {
                <i32>::sse_encode(36, serializer);
                <String>::sse_encode(latex, serializer);
            }
            crate::api::editor_api::EditorIntent::TapBlock {
                block_id,
                caret_index,
            } => {
                <i32>::sse_encode(37, serializer);
                <u32>::sse_encode(block_id, serializer);
                <u32>::sse_encode(caret_index, serializer);
            }
            crate::api::editor_api::EditorIntent::DragStart {
                block_id,
                caret_index,
            } => {
                <i32>::sse_encode(38, serializer);
                <u32>::sse_encode(block_id, serializer);
                <u32>::sse_encode(caret_index, serializer);
            }
            crate::api::editor_api::EditorIntent::DragUpdate {
                block_id,
                caret_index,
            } => {
                <i32>::sse_encode(39, serializer);
                <u32>::sse_encode(block_id, serializer);
                <u32>::sse_encode(caret_index, serializer);
            }
            crate::api::editor_api::EditorIntent::Undo => {
                <i32>::sse_encode(40, serializer);
            }
            crate::api::editor_api::EditorIntent::Redo => {
                <i32>::sse_encode(41, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::editor_layout::EditorLayout {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::editor_layout::BlockLayout>::sse_encode(self.root, serializer);
        <Vec<crate::api::math_api::MathNode>>::sse_encode(self.untagged, serializer);
    }
}

impl SseEncode for crate::api::editor_api::EditorSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::editor_layout::EditorLayout>::sse_encode(self.editor_layout, serializer);
        <String>::sse_encode(self.latex, serializer);
        <bool>::sse_encode(self.in_command_input, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::editor_layout::BlockLayout> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::editor_layout::BlockLayout>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::math_api::MathNode> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::math_api::MathNode>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::editor_layout::NodeLayout> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::editor_layout::NodeLayout>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::math_api::PathCommand> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::math_api::PathCommand>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <f64>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::math_api::MathLayout {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.width, serializer);
        <f64>::sse_encode(self.height, serializer);
        <f64>::sse_encode(self.depth, serializer);
        <Vec<crate::api::math_api::MathNode>>::sse_encode(self.nodes, serializer);
    }
}

impl SseEncode for crate::api::math_api::MathNode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::math_api::MathNode::Glyph {
                codepoint,
                x,
                y,
                font_name,
                scale,
                width,
                color,
                node_id,
            } => {
                <i32>::sse_encode(0, serializer);
                <u32>::sse_encode(codepoint, serializer);
                <f64>::sse_encode(x, serializer);
                <f64>::sse_encode(y, serializer);
                <String>::sse_encode(font_name, serializer);
                <f64>::sse_encode(scale, serializer);
                <f64>::sse_encode(width, serializer);
                <Option<String>>::sse_encode(color, serializer);
                <Option<u32>>::sse_encode(node_id, serializer);
            }
            crate::api::math_api::MathNode::Rule {
                x,
                y,
                width,
                height,
                color,
                node_id,
            } => {
                <i32>::sse_encode(1, serializer);
                <f64>::sse_encode(x, serializer);
                <f64>::sse_encode(y, serializer);
                <f64>::sse_encode(width, serializer);
                <f64>::sse_encode(height, serializer);
                <Option<String>>::sse_encode(color, serializer);
                <Option<u32>>::sse_encode(node_id, serializer);
            }
            crate::api::math_api::MathNode::SvgPath {
                x,
                y,
                width,
                height,
                view_box_x,
                view_box_y,
                view_box_width,
                view_box_height,
                commands,
                node_id,
            } => {
                <i32>::sse_encode(2, serializer);
                <f64>::sse_encode(x, serializer);
                <f64>::sse_encode(y, serializer);
                <f64>::sse_encode(width, serializer);
                <f64>::sse_encode(height, serializer);
                <f64>::sse_encode(view_box_x, serializer);
                <f64>::sse_encode(view_box_y, serializer);
                <f64>::sse_encode(view_box_width, serializer);
                <f64>::sse_encode(view_box_height, serializer);
                <Vec<crate::api::math_api::PathCommand>>::sse_encode(commands, serializer);
                <Option<u32>>::sse_encode(node_id, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::editor_layout::NodeLayout {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::editor_layout::NodeLayout::Leaf {
                node_id,
                glyphs,
                width,
                height,
                depth,
                left_x,
            } => {
                <i32>::sse_encode(0, serializer);
                <u32>::sse_encode(node_id, serializer);
                <Vec<crate::api::math_api::MathNode>>::sse_encode(glyphs, serializer);
                <f64>::sse_encode(width, serializer);
                <f64>::sse_encode(height, serializer);
                <f64>::sse_encode(depth, serializer);
                <f64>::sse_encode(left_x, serializer);
            }
            crate::api::editor_layout::NodeLayout::Command {
                node_id,
                kind,
                width,
                height,
                depth,
                left_x,
                child_blocks,
                decorations,
            } => {
                <i32>::sse_encode(1, serializer);
                <u32>::sse_encode(node_id, serializer);
                <crate::api::editor_layout::CommandLayoutKind>::sse_encode(kind, serializer);
                <f64>::sse_encode(width, serializer);
                <f64>::sse_encode(height, serializer);
                <f64>::sse_encode(depth, serializer);
                <f64>::sse_encode(left_x, serializer);
                <Vec<crate::api::editor_layout::BlockLayout>>::sse_encode(child_blocks, serializer);
                <Vec<crate::api::math_api::MathNode>>::sse_encode(decorations, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::editor_layout::BlockSelection> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::editor_layout::BlockSelection>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::math_api::PathCommand {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::math_api::PathCommand::MoveTo { x, y } => {
                <i32>::sse_encode(0, serializer);
                <f64>::sse_encode(x, serializer);
                <f64>::sse_encode(y, serializer);
            }
            crate::api::math_api::PathCommand::LineTo { x, y } => {
                <i32>::sse_encode(1, serializer);
                <f64>::sse_encode(x, serializer);
                <f64>::sse_encode(y, serializer);
            }
            crate::api::math_api::PathCommand::CubicTo {
                x1,
                y1,
                x2,
                y2,
                x,
                y,
            } => {
                <i32>::sse_encode(2, serializer);
                <f64>::sse_encode(x1, serializer);
                <f64>::sse_encode(y1, serializer);
                <f64>::sse_encode(x2, serializer);
                <f64>::sse_encode(y2, serializer);
                <f64>::sse_encode(x, serializer);
                <f64>::sse_encode(y, serializer);
            }
            crate::api::math_api::PathCommand::QuadTo { x1, y1, x, y } => {
                <i32>::sse_encode(3, serializer);
                <f64>::sse_encode(x1, serializer);
                <f64>::sse_encode(y1, serializer);
                <f64>::sse_encode(x, serializer);
                <f64>::sse_encode(y, serializer);
            }
            crate::api::math_api::PathCommand::Close => {
                <i32>::sse_encode(4, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
