// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/editor_api.dart';
import 'api/editor_layout.dart';
import 'api/math_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BlockLayout dco_decode_block_layout(dynamic raw);

  @protected
  BlockSelection dco_decode_block_selection(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BlockSelection dco_decode_box_autoadd_block_selection(dynamic raw);

  @protected
  CommandLayoutKind dco_decode_box_autoadd_command_layout_kind(dynamic raw);

  @protected
  EditorIntent dco_decode_box_autoadd_editor_intent(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CommandLayoutKind dco_decode_command_layout_kind(dynamic raw);

  @protected
  EditorIntent dco_decode_editor_intent(dynamic raw);

  @protected
  EditorLayout dco_decode_editor_layout(dynamic raw);

  @protected
  EditorSnapshot dco_decode_editor_snapshot(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  List<BlockLayout> dco_decode_list_block_layout(dynamic raw);

  @protected
  List<MathNode> dco_decode_list_math_node(dynamic raw);

  @protected
  List<NodeLayout> dco_decode_list_node_layout(dynamic raw);

  @protected
  List<PathCommand> dco_decode_list_path_command(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MathLayout dco_decode_math_layout(dynamic raw);

  @protected
  MathNode dco_decode_math_node(dynamic raw);

  @protected
  NodeLayout dco_decode_node_layout(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BlockSelection? dco_decode_opt_box_autoadd_block_selection(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PathCommand dco_decode_path_command(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BlockLayout sse_decode_block_layout(SseDeserializer deserializer);

  @protected
  BlockSelection sse_decode_block_selection(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BlockSelection sse_decode_box_autoadd_block_selection(
    SseDeserializer deserializer,
  );

  @protected
  CommandLayoutKind sse_decode_box_autoadd_command_layout_kind(
    SseDeserializer deserializer,
  );

  @protected
  EditorIntent sse_decode_box_autoadd_editor_intent(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CommandLayoutKind sse_decode_command_layout_kind(
    SseDeserializer deserializer,
  );

  @protected
  EditorIntent sse_decode_editor_intent(SseDeserializer deserializer);

  @protected
  EditorLayout sse_decode_editor_layout(SseDeserializer deserializer);

  @protected
  EditorSnapshot sse_decode_editor_snapshot(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  List<BlockLayout> sse_decode_list_block_layout(SseDeserializer deserializer);

  @protected
  List<MathNode> sse_decode_list_math_node(SseDeserializer deserializer);

  @protected
  List<NodeLayout> sse_decode_list_node_layout(SseDeserializer deserializer);

  @protected
  List<PathCommand> sse_decode_list_path_command(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MathLayout sse_decode_math_layout(SseDeserializer deserializer);

  @protected
  MathNode sse_decode_math_node(SseDeserializer deserializer);

  @protected
  NodeLayout sse_decode_node_layout(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BlockSelection? sse_decode_opt_box_autoadd_block_selection(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PathCommand sse_decode_path_command(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_block_layout(BlockLayout self, SseSerializer serializer);

  @protected
  void sse_encode_block_selection(
    BlockSelection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_block_selection(
    BlockSelection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_command_layout_kind(
    CommandLayoutKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_editor_intent(
    EditorIntent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_command_layout_kind(
    CommandLayoutKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_editor_intent(EditorIntent self, SseSerializer serializer);

  @protected
  void sse_encode_editor_layout(EditorLayout self, SseSerializer serializer);

  @protected
  void sse_encode_editor_snapshot(
    EditorSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_block_layout(
    List<BlockLayout> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_math_node(List<MathNode> self, SseSerializer serializer);

  @protected
  void sse_encode_list_node_layout(
    List<NodeLayout> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_path_command(
    List<PathCommand> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_math_layout(MathLayout self, SseSerializer serializer);

  @protected
  void sse_encode_math_node(MathNode self, SseSerializer serializer);

  @protected
  void sse_encode_node_layout(NodeLayout self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_block_selection(
    BlockSelection? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_path_command(PathCommand self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
