// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/editor_api.dart';
import 'api/editor_layout.dart';
import 'api/math_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiMathApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 97078151;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'math_view',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiEditorApiCloseEditor({required String id});

  String crateApiEditorApiCreateEditor();

  String crateApiEditorApiCreateEditorFromLatex({required String latex});

  EditorSnapshot crateApiEditorApiDispatchEditor({
    required String id,
    required EditorIntent intent,
    required bool displayMode,
  });

  EditorSnapshot crateApiEditorApiGetEditorSnapshot({
    required String id,
    required bool displayMode,
  });

  Future<void> crateApiMathApiInitApp();

  MathLayout crateApiMathApiLayoutMath({
    required String latex,
    required bool displayMode,
  });

  EditorLayout crateApiMathApiLayoutMathTree({
    required String latex,
    required bool displayMode,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiEditorApiCloseEditor({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorApiCloseEditorConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorApiCloseEditorConstMeta =>
      const TaskConstMeta(debugName: "close_editor", argNames: ["id"]);

  @override
  String crateApiEditorApiCreateEditor() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorApiCreateEditorConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorApiCreateEditorConstMeta =>
      const TaskConstMeta(debugName: "create_editor", argNames: []);

  @override
  String crateApiEditorApiCreateEditorFromLatex({required String latex}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(latex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorApiCreateEditorFromLatexConstMeta,
        argValues: [latex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorApiCreateEditorFromLatexConstMeta =>
      const TaskConstMeta(
        debugName: "create_editor_from_latex",
        argNames: ["latex"],
      );

  @override
  EditorSnapshot crateApiEditorApiDispatchEditor({
    required String id,
    required EditorIntent intent,
    required bool displayMode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_box_autoadd_editor_intent(intent, serializer);
          sse_encode_bool(displayMode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_editor_snapshot,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorApiDispatchEditorConstMeta,
        argValues: [id, intent, displayMode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorApiDispatchEditorConstMeta =>
      const TaskConstMeta(
        debugName: "dispatch_editor",
        argNames: ["id", "intent", "displayMode"],
      );

  @override
  EditorSnapshot crateApiEditorApiGetEditorSnapshot({
    required String id,
    required bool displayMode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_bool(displayMode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_editor_snapshot,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorApiGetEditorSnapshotConstMeta,
        argValues: [id, displayMode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorApiGetEditorSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "get_editor_snapshot",
        argNames: ["id", "displayMode"],
      );

  @override
  Future<void> crateApiMathApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMathApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMathApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  MathLayout crateApiMathApiLayoutMath({
    required String latex,
    required bool displayMode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(latex, serializer);
          sse_encode_bool(displayMode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_math_layout,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMathApiLayoutMathConstMeta,
        argValues: [latex, displayMode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMathApiLayoutMathConstMeta => const TaskConstMeta(
    debugName: "layout_math",
    argNames: ["latex", "displayMode"],
  );

  @override
  EditorLayout crateApiMathApiLayoutMathTree({
    required String latex,
    required bool displayMode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(latex, serializer);
          sse_encode_bool(displayMode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_editor_layout,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMathApiLayoutMathTreeConstMeta,
        argValues: [latex, displayMode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMathApiLayoutMathTreeConstMeta =>
      const TaskConstMeta(
        debugName: "layout_math_tree",
        argNames: ["latex", "displayMode"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BlockLayout dco_decode_block_layout(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BlockLayout(
      blockId: dco_decode_u_32(arr[0]),
      width: dco_decode_f_64(arr[1]),
      height: dco_decode_f_64(arr[2]),
      depth: dco_decode_f_64(arr[3]),
      children: dco_decode_list_node_layout(arr[4]),
      cursorIndex: dco_decode_opt_box_autoadd_u_32(arr[5]),
      selection: dco_decode_opt_box_autoadd_block_selection(arr[6]),
    );
  }

  @protected
  BlockSelection dco_decode_block_selection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BlockSelection(
      start: dco_decode_u_32(arr[0]),
      end: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BlockSelection dco_decode_box_autoadd_block_selection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_block_selection(raw);
  }

  @protected
  CommandLayoutKind dco_decode_box_autoadd_command_layout_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_command_layout_kind(raw);
  }

  @protected
  EditorIntent dco_decode_box_autoadd_editor_intent(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_editor_intent(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CommandLayoutKind dco_decode_command_layout_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CommandLayoutKind_Frac();
      case 1:
        return CommandLayoutKind_Sqrt();
      case 2:
        return CommandLayoutKind_NthRoot();
      case 3:
        return CommandLayoutKind_Sup();
      case 4:
        return CommandLayoutKind_Sub();
      case 5:
        return CommandLayoutKind_SupSub();
      case 6:
        return CommandLayoutKind_Overline();
      case 7:
        return CommandLayoutKind_Underline();
      case 8:
        return CommandLayoutKind_LeftRight();
      case 9:
        return CommandLayoutKind_SumLike();
      case 10:
        return CommandLayoutKind_Matrix(
          rows: dco_decode_u_32(raw[1]),
          cols: dco_decode_u_32(raw[2]),
        );
      case 11:
        return CommandLayoutKind_Text();
      case 12:
        return CommandLayoutKind_Other();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  EditorIntent dco_decode_editor_intent(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return EditorIntent_InsertSymbol(ch: dco_decode_String(raw[1]));
      case 1:
        return EditorIntent_InsertFrac();
      case 2:
        return EditorIntent_InsertSqrt();
      case 3:
        return EditorIntent_InsertNthRoot();
      case 4:
        return EditorIntent_InsertSup();
      case 5:
        return EditorIntent_InsertSub();
      case 6:
        return EditorIntent_InsertParentheses();
      case 7:
        return EditorIntent_InsertBrackets();
      case 8:
        return EditorIntent_InsertBraces();
      case 9:
        return EditorIntent_InsertAbs();
      case 10:
        return EditorIntent_InsertSum();
      case 11:
        return EditorIntent_InsertProduct();
      case 12:
        return EditorIntent_InsertIntegral();
      case 13:
        return EditorIntent_InsertLimit();
      case 14:
        return EditorIntent_InsertOverline();
      case 15:
        return EditorIntent_InsertUnderline();
      case 16:
        return EditorIntent_InsertText();
      case 17:
        return EditorIntent_MoveLeft();
      case 18:
        return EditorIntent_MoveRight();
      case 19:
        return EditorIntent_MoveUp();
      case 20:
        return EditorIntent_MoveDown();
      case 21:
        return EditorIntent_MoveToStart();
      case 22:
        return EditorIntent_MoveToEnd();
      case 23:
        return EditorIntent_SelectLeft();
      case 24:
        return EditorIntent_SelectRight();
      case 25:
        return EditorIntent_SelectAll();
      case 26:
        return EditorIntent_DeleteBackward();
      case 27:
        return EditorIntent_DeleteForward();
      case 28:
        return EditorIntent_SetLatex(latex: dco_decode_String(raw[1]));
      case 29:
        return EditorIntent_TapBlock(
          blockId: dco_decode_u_32(raw[1]),
          caretIndex: dco_decode_u_32(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  EditorLayout dco_decode_editor_layout(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EditorLayout(
      root: dco_decode_block_layout(arr[0]),
      untagged: dco_decode_list_math_node(arr[1]),
    );
  }

  @protected
  EditorSnapshot dco_decode_editor_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EditorSnapshot(
      editorLayout: dco_decode_editor_layout(arr[0]),
      latex: dco_decode_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<BlockLayout> dco_decode_list_block_layout(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_block_layout).toList();
  }

  @protected
  List<MathNode> dco_decode_list_math_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_math_node).toList();
  }

  @protected
  List<NodeLayout> dco_decode_list_node_layout(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_node_layout).toList();
  }

  @protected
  List<PathCommand> dco_decode_list_path_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_path_command).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MathLayout dco_decode_math_layout(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MathLayout(
      width: dco_decode_f_64(arr[0]),
      height: dco_decode_f_64(arr[1]),
      depth: dco_decode_f_64(arr[2]),
      nodes: dco_decode_list_math_node(arr[3]),
    );
  }

  @protected
  MathNode dco_decode_math_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MathNode_Glyph(
          codepoint: dco_decode_u_32(raw[1]),
          x: dco_decode_f_64(raw[2]),
          y: dco_decode_f_64(raw[3]),
          fontName: dco_decode_String(raw[4]),
          scale: dco_decode_f_64(raw[5]),
          color: dco_decode_opt_String(raw[6]),
          nodeId: dco_decode_opt_box_autoadd_u_32(raw[7]),
        );
      case 1:
        return MathNode_Rule(
          x: dco_decode_f_64(raw[1]),
          y: dco_decode_f_64(raw[2]),
          width: dco_decode_f_64(raw[3]),
          height: dco_decode_f_64(raw[4]),
          color: dco_decode_opt_String(raw[5]),
          nodeId: dco_decode_opt_box_autoadd_u_32(raw[6]),
        );
      case 2:
        return MathNode_SvgPath(
          x: dco_decode_f_64(raw[1]),
          y: dco_decode_f_64(raw[2]),
          width: dco_decode_f_64(raw[3]),
          height: dco_decode_f_64(raw[4]),
          viewBoxX: dco_decode_f_64(raw[5]),
          viewBoxY: dco_decode_f_64(raw[6]),
          viewBoxWidth: dco_decode_f_64(raw[7]),
          viewBoxHeight: dco_decode_f_64(raw[8]),
          commands: dco_decode_list_path_command(raw[9]),
          nodeId: dco_decode_opt_box_autoadd_u_32(raw[10]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  NodeLayout dco_decode_node_layout(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return NodeLayout_Leaf(
          nodeId: dco_decode_u_32(raw[1]),
          glyphs: dco_decode_list_math_node(raw[2]),
          width: dco_decode_f_64(raw[3]),
          height: dco_decode_f_64(raw[4]),
          depth: dco_decode_f_64(raw[5]),
        );
      case 1:
        return NodeLayout_Command(
          nodeId: dco_decode_u_32(raw[1]),
          kind: dco_decode_box_autoadd_command_layout_kind(raw[2]),
          width: dco_decode_f_64(raw[3]),
          height: dco_decode_f_64(raw[4]),
          depth: dco_decode_f_64(raw[5]),
          childBlocks: dco_decode_list_block_layout(raw[6]),
          decorations: dco_decode_list_math_node(raw[7]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BlockSelection? dco_decode_opt_box_autoadd_block_selection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_block_selection(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PathCommand dco_decode_path_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return PathCommand_MoveTo(
          x: dco_decode_f_64(raw[1]),
          y: dco_decode_f_64(raw[2]),
        );
      case 1:
        return PathCommand_LineTo(
          x: dco_decode_f_64(raw[1]),
          y: dco_decode_f_64(raw[2]),
        );
      case 2:
        return PathCommand_CubicTo(
          x1: dco_decode_f_64(raw[1]),
          y1: dco_decode_f_64(raw[2]),
          x2: dco_decode_f_64(raw[3]),
          y2: dco_decode_f_64(raw[4]),
          x: dco_decode_f_64(raw[5]),
          y: dco_decode_f_64(raw[6]),
        );
      case 3:
        return PathCommand_QuadTo(
          x1: dco_decode_f_64(raw[1]),
          y1: dco_decode_f_64(raw[2]),
          x: dco_decode_f_64(raw[3]),
          y: dco_decode_f_64(raw[4]),
        );
      case 4:
        return PathCommand_Close();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BlockLayout sse_decode_block_layout(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_blockId = sse_decode_u_32(deserializer);
    var var_width = sse_decode_f_64(deserializer);
    var var_height = sse_decode_f_64(deserializer);
    var var_depth = sse_decode_f_64(deserializer);
    var var_children = sse_decode_list_node_layout(deserializer);
    var var_cursorIndex = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_selection = sse_decode_opt_box_autoadd_block_selection(
      deserializer,
    );
    return BlockLayout(
      blockId: var_blockId,
      width: var_width,
      height: var_height,
      depth: var_depth,
      children: var_children,
      cursorIndex: var_cursorIndex,
      selection: var_selection,
    );
  }

  @protected
  BlockSelection sse_decode_block_selection(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_start = sse_decode_u_32(deserializer);
    var var_end = sse_decode_u_32(deserializer);
    return BlockSelection(start: var_start, end: var_end);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BlockSelection sse_decode_box_autoadd_block_selection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_block_selection(deserializer));
  }

  @protected
  CommandLayoutKind sse_decode_box_autoadd_command_layout_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_command_layout_kind(deserializer));
  }

  @protected
  EditorIntent sse_decode_box_autoadd_editor_intent(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_editor_intent(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CommandLayoutKind sse_decode_command_layout_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return CommandLayoutKind_Frac();
      case 1:
        return CommandLayoutKind_Sqrt();
      case 2:
        return CommandLayoutKind_NthRoot();
      case 3:
        return CommandLayoutKind_Sup();
      case 4:
        return CommandLayoutKind_Sub();
      case 5:
        return CommandLayoutKind_SupSub();
      case 6:
        return CommandLayoutKind_Overline();
      case 7:
        return CommandLayoutKind_Underline();
      case 8:
        return CommandLayoutKind_LeftRight();
      case 9:
        return CommandLayoutKind_SumLike();
      case 10:
        var var_rows = sse_decode_u_32(deserializer);
        var var_cols = sse_decode_u_32(deserializer);
        return CommandLayoutKind_Matrix(rows: var_rows, cols: var_cols);
      case 11:
        return CommandLayoutKind_Text();
      case 12:
        return CommandLayoutKind_Other();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  EditorIntent sse_decode_editor_intent(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_ch = sse_decode_String(deserializer);
        return EditorIntent_InsertSymbol(ch: var_ch);
      case 1:
        return EditorIntent_InsertFrac();
      case 2:
        return EditorIntent_InsertSqrt();
      case 3:
        return EditorIntent_InsertNthRoot();
      case 4:
        return EditorIntent_InsertSup();
      case 5:
        return EditorIntent_InsertSub();
      case 6:
        return EditorIntent_InsertParentheses();
      case 7:
        return EditorIntent_InsertBrackets();
      case 8:
        return EditorIntent_InsertBraces();
      case 9:
        return EditorIntent_InsertAbs();
      case 10:
        return EditorIntent_InsertSum();
      case 11:
        return EditorIntent_InsertProduct();
      case 12:
        return EditorIntent_InsertIntegral();
      case 13:
        return EditorIntent_InsertLimit();
      case 14:
        return EditorIntent_InsertOverline();
      case 15:
        return EditorIntent_InsertUnderline();
      case 16:
        return EditorIntent_InsertText();
      case 17:
        return EditorIntent_MoveLeft();
      case 18:
        return EditorIntent_MoveRight();
      case 19:
        return EditorIntent_MoveUp();
      case 20:
        return EditorIntent_MoveDown();
      case 21:
        return EditorIntent_MoveToStart();
      case 22:
        return EditorIntent_MoveToEnd();
      case 23:
        return EditorIntent_SelectLeft();
      case 24:
        return EditorIntent_SelectRight();
      case 25:
        return EditorIntent_SelectAll();
      case 26:
        return EditorIntent_DeleteBackward();
      case 27:
        return EditorIntent_DeleteForward();
      case 28:
        var var_latex = sse_decode_String(deserializer);
        return EditorIntent_SetLatex(latex: var_latex);
      case 29:
        var var_blockId = sse_decode_u_32(deserializer);
        var var_caretIndex = sse_decode_u_32(deserializer);
        return EditorIntent_TapBlock(
          blockId: var_blockId,
          caretIndex: var_caretIndex,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  EditorLayout sse_decode_editor_layout(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_root = sse_decode_block_layout(deserializer);
    var var_untagged = sse_decode_list_math_node(deserializer);
    return EditorLayout(root: var_root, untagged: var_untagged);
  }

  @protected
  EditorSnapshot sse_decode_editor_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_editorLayout = sse_decode_editor_layout(deserializer);
    var var_latex = sse_decode_String(deserializer);
    return EditorSnapshot(editorLayout: var_editorLayout, latex: var_latex);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<BlockLayout> sse_decode_list_block_layout(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BlockLayout>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_block_layout(deserializer));
    }
    return ans_;
  }

  @protected
  List<MathNode> sse_decode_list_math_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MathNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_math_node(deserializer));
    }
    return ans_;
  }

  @protected
  List<NodeLayout> sse_decode_list_node_layout(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NodeLayout>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_node_layout(deserializer));
    }
    return ans_;
  }

  @protected
  List<PathCommand> sse_decode_list_path_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PathCommand>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_path_command(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MathLayout sse_decode_math_layout(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_f_64(deserializer);
    var var_height = sse_decode_f_64(deserializer);
    var var_depth = sse_decode_f_64(deserializer);
    var var_nodes = sse_decode_list_math_node(deserializer);
    return MathLayout(
      width: var_width,
      height: var_height,
      depth: var_depth,
      nodes: var_nodes,
    );
  }

  @protected
  MathNode sse_decode_math_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_codepoint = sse_decode_u_32(deserializer);
        var var_x = sse_decode_f_64(deserializer);
        var var_y = sse_decode_f_64(deserializer);
        var var_fontName = sse_decode_String(deserializer);
        var var_scale = sse_decode_f_64(deserializer);
        var var_color = sse_decode_opt_String(deserializer);
        var var_nodeId = sse_decode_opt_box_autoadd_u_32(deserializer);
        return MathNode_Glyph(
          codepoint: var_codepoint,
          x: var_x,
          y: var_y,
          fontName: var_fontName,
          scale: var_scale,
          color: var_color,
          nodeId: var_nodeId,
        );
      case 1:
        var var_x = sse_decode_f_64(deserializer);
        var var_y = sse_decode_f_64(deserializer);
        var var_width = sse_decode_f_64(deserializer);
        var var_height = sse_decode_f_64(deserializer);
        var var_color = sse_decode_opt_String(deserializer);
        var var_nodeId = sse_decode_opt_box_autoadd_u_32(deserializer);
        return MathNode_Rule(
          x: var_x,
          y: var_y,
          width: var_width,
          height: var_height,
          color: var_color,
          nodeId: var_nodeId,
        );
      case 2:
        var var_x = sse_decode_f_64(deserializer);
        var var_y = sse_decode_f_64(deserializer);
        var var_width = sse_decode_f_64(deserializer);
        var var_height = sse_decode_f_64(deserializer);
        var var_viewBoxX = sse_decode_f_64(deserializer);
        var var_viewBoxY = sse_decode_f_64(deserializer);
        var var_viewBoxWidth = sse_decode_f_64(deserializer);
        var var_viewBoxHeight = sse_decode_f_64(deserializer);
        var var_commands = sse_decode_list_path_command(deserializer);
        var var_nodeId = sse_decode_opt_box_autoadd_u_32(deserializer);
        return MathNode_SvgPath(
          x: var_x,
          y: var_y,
          width: var_width,
          height: var_height,
          viewBoxX: var_viewBoxX,
          viewBoxY: var_viewBoxY,
          viewBoxWidth: var_viewBoxWidth,
          viewBoxHeight: var_viewBoxHeight,
          commands: var_commands,
          nodeId: var_nodeId,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  NodeLayout sse_decode_node_layout(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_nodeId = sse_decode_u_32(deserializer);
        var var_glyphs = sse_decode_list_math_node(deserializer);
        var var_width = sse_decode_f_64(deserializer);
        var var_height = sse_decode_f_64(deserializer);
        var var_depth = sse_decode_f_64(deserializer);
        return NodeLayout_Leaf(
          nodeId: var_nodeId,
          glyphs: var_glyphs,
          width: var_width,
          height: var_height,
          depth: var_depth,
        );
      case 1:
        var var_nodeId = sse_decode_u_32(deserializer);
        var var_kind = sse_decode_box_autoadd_command_layout_kind(deserializer);
        var var_width = sse_decode_f_64(deserializer);
        var var_height = sse_decode_f_64(deserializer);
        var var_depth = sse_decode_f_64(deserializer);
        var var_childBlocks = sse_decode_list_block_layout(deserializer);
        var var_decorations = sse_decode_list_math_node(deserializer);
        return NodeLayout_Command(
          nodeId: var_nodeId,
          kind: var_kind,
          width: var_width,
          height: var_height,
          depth: var_depth,
          childBlocks: var_childBlocks,
          decorations: var_decorations,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BlockSelection? sse_decode_opt_box_autoadd_block_selection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_block_selection(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PathCommand sse_decode_path_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_x = sse_decode_f_64(deserializer);
        var var_y = sse_decode_f_64(deserializer);
        return PathCommand_MoveTo(x: var_x, y: var_y);
      case 1:
        var var_x = sse_decode_f_64(deserializer);
        var var_y = sse_decode_f_64(deserializer);
        return PathCommand_LineTo(x: var_x, y: var_y);
      case 2:
        var var_x1 = sse_decode_f_64(deserializer);
        var var_y1 = sse_decode_f_64(deserializer);
        var var_x2 = sse_decode_f_64(deserializer);
        var var_y2 = sse_decode_f_64(deserializer);
        var var_x = sse_decode_f_64(deserializer);
        var var_y = sse_decode_f_64(deserializer);
        return PathCommand_CubicTo(
          x1: var_x1,
          y1: var_y1,
          x2: var_x2,
          y2: var_y2,
          x: var_x,
          y: var_y,
        );
      case 3:
        var var_x1 = sse_decode_f_64(deserializer);
        var var_y1 = sse_decode_f_64(deserializer);
        var var_x = sse_decode_f_64(deserializer);
        var var_y = sse_decode_f_64(deserializer);
        return PathCommand_QuadTo(x1: var_x1, y1: var_y1, x: var_x, y: var_y);
      case 4:
        return PathCommand_Close();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_block_layout(BlockLayout self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.blockId, serializer);
    sse_encode_f_64(self.width, serializer);
    sse_encode_f_64(self.height, serializer);
    sse_encode_f_64(self.depth, serializer);
    sse_encode_list_node_layout(self.children, serializer);
    sse_encode_opt_box_autoadd_u_32(self.cursorIndex, serializer);
    sse_encode_opt_box_autoadd_block_selection(self.selection, serializer);
  }

  @protected
  void sse_encode_block_selection(
    BlockSelection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.start, serializer);
    sse_encode_u_32(self.end, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_block_selection(
    BlockSelection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_block_selection(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_command_layout_kind(
    CommandLayoutKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_command_layout_kind(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_editor_intent(
    EditorIntent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_editor_intent(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_command_layout_kind(
    CommandLayoutKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CommandLayoutKind_Frac():
        sse_encode_i_32(0, serializer);
      case CommandLayoutKind_Sqrt():
        sse_encode_i_32(1, serializer);
      case CommandLayoutKind_NthRoot():
        sse_encode_i_32(2, serializer);
      case CommandLayoutKind_Sup():
        sse_encode_i_32(3, serializer);
      case CommandLayoutKind_Sub():
        sse_encode_i_32(4, serializer);
      case CommandLayoutKind_SupSub():
        sse_encode_i_32(5, serializer);
      case CommandLayoutKind_Overline():
        sse_encode_i_32(6, serializer);
      case CommandLayoutKind_Underline():
        sse_encode_i_32(7, serializer);
      case CommandLayoutKind_LeftRight():
        sse_encode_i_32(8, serializer);
      case CommandLayoutKind_SumLike():
        sse_encode_i_32(9, serializer);
      case CommandLayoutKind_Matrix(rows: final rows, cols: final cols):
        sse_encode_i_32(10, serializer);
        sse_encode_u_32(rows, serializer);
        sse_encode_u_32(cols, serializer);
      case CommandLayoutKind_Text():
        sse_encode_i_32(11, serializer);
      case CommandLayoutKind_Other():
        sse_encode_i_32(12, serializer);
    }
  }

  @protected
  void sse_encode_editor_intent(EditorIntent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case EditorIntent_InsertSymbol(ch: final ch):
        sse_encode_i_32(0, serializer);
        sse_encode_String(ch, serializer);
      case EditorIntent_InsertFrac():
        sse_encode_i_32(1, serializer);
      case EditorIntent_InsertSqrt():
        sse_encode_i_32(2, serializer);
      case EditorIntent_InsertNthRoot():
        sse_encode_i_32(3, serializer);
      case EditorIntent_InsertSup():
        sse_encode_i_32(4, serializer);
      case EditorIntent_InsertSub():
        sse_encode_i_32(5, serializer);
      case EditorIntent_InsertParentheses():
        sse_encode_i_32(6, serializer);
      case EditorIntent_InsertBrackets():
        sse_encode_i_32(7, serializer);
      case EditorIntent_InsertBraces():
        sse_encode_i_32(8, serializer);
      case EditorIntent_InsertAbs():
        sse_encode_i_32(9, serializer);
      case EditorIntent_InsertSum():
        sse_encode_i_32(10, serializer);
      case EditorIntent_InsertProduct():
        sse_encode_i_32(11, serializer);
      case EditorIntent_InsertIntegral():
        sse_encode_i_32(12, serializer);
      case EditorIntent_InsertLimit():
        sse_encode_i_32(13, serializer);
      case EditorIntent_InsertOverline():
        sse_encode_i_32(14, serializer);
      case EditorIntent_InsertUnderline():
        sse_encode_i_32(15, serializer);
      case EditorIntent_InsertText():
        sse_encode_i_32(16, serializer);
      case EditorIntent_MoveLeft():
        sse_encode_i_32(17, serializer);
      case EditorIntent_MoveRight():
        sse_encode_i_32(18, serializer);
      case EditorIntent_MoveUp():
        sse_encode_i_32(19, serializer);
      case EditorIntent_MoveDown():
        sse_encode_i_32(20, serializer);
      case EditorIntent_MoveToStart():
        sse_encode_i_32(21, serializer);
      case EditorIntent_MoveToEnd():
        sse_encode_i_32(22, serializer);
      case EditorIntent_SelectLeft():
        sse_encode_i_32(23, serializer);
      case EditorIntent_SelectRight():
        sse_encode_i_32(24, serializer);
      case EditorIntent_SelectAll():
        sse_encode_i_32(25, serializer);
      case EditorIntent_DeleteBackward():
        sse_encode_i_32(26, serializer);
      case EditorIntent_DeleteForward():
        sse_encode_i_32(27, serializer);
      case EditorIntent_SetLatex(latex: final latex):
        sse_encode_i_32(28, serializer);
        sse_encode_String(latex, serializer);
      case EditorIntent_TapBlock(
        blockId: final blockId,
        caretIndex: final caretIndex,
      ):
        sse_encode_i_32(29, serializer);
        sse_encode_u_32(blockId, serializer);
        sse_encode_u_32(caretIndex, serializer);
    }
  }

  @protected
  void sse_encode_editor_layout(EditorLayout self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_block_layout(self.root, serializer);
    sse_encode_list_math_node(self.untagged, serializer);
  }

  @protected
  void sse_encode_editor_snapshot(
    EditorSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_editor_layout(self.editorLayout, serializer);
    sse_encode_String(self.latex, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_block_layout(
    List<BlockLayout> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_block_layout(item, serializer);
    }
  }

  @protected
  void sse_encode_list_math_node(
    List<MathNode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_math_node(item, serializer);
    }
  }

  @protected
  void sse_encode_list_node_layout(
    List<NodeLayout> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_node_layout(item, serializer);
    }
  }

  @protected
  void sse_encode_list_path_command(
    List<PathCommand> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_path_command(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_math_layout(MathLayout self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.width, serializer);
    sse_encode_f_64(self.height, serializer);
    sse_encode_f_64(self.depth, serializer);
    sse_encode_list_math_node(self.nodes, serializer);
  }

  @protected
  void sse_encode_math_node(MathNode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MathNode_Glyph(
        codepoint: final codepoint,
        x: final x,
        y: final y,
        fontName: final fontName,
        scale: final scale,
        color: final color,
        nodeId: final nodeId,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_u_32(codepoint, serializer);
        sse_encode_f_64(x, serializer);
        sse_encode_f_64(y, serializer);
        sse_encode_String(fontName, serializer);
        sse_encode_f_64(scale, serializer);
        sse_encode_opt_String(color, serializer);
        sse_encode_opt_box_autoadd_u_32(nodeId, serializer);
      case MathNode_Rule(
        x: final x,
        y: final y,
        width: final width,
        height: final height,
        color: final color,
        nodeId: final nodeId,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_f_64(x, serializer);
        sse_encode_f_64(y, serializer);
        sse_encode_f_64(width, serializer);
        sse_encode_f_64(height, serializer);
        sse_encode_opt_String(color, serializer);
        sse_encode_opt_box_autoadd_u_32(nodeId, serializer);
      case MathNode_SvgPath(
        x: final x,
        y: final y,
        width: final width,
        height: final height,
        viewBoxX: final viewBoxX,
        viewBoxY: final viewBoxY,
        viewBoxWidth: final viewBoxWidth,
        viewBoxHeight: final viewBoxHeight,
        commands: final commands,
        nodeId: final nodeId,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_f_64(x, serializer);
        sse_encode_f_64(y, serializer);
        sse_encode_f_64(width, serializer);
        sse_encode_f_64(height, serializer);
        sse_encode_f_64(viewBoxX, serializer);
        sse_encode_f_64(viewBoxY, serializer);
        sse_encode_f_64(viewBoxWidth, serializer);
        sse_encode_f_64(viewBoxHeight, serializer);
        sse_encode_list_path_command(commands, serializer);
        sse_encode_opt_box_autoadd_u_32(nodeId, serializer);
    }
  }

  @protected
  void sse_encode_node_layout(NodeLayout self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case NodeLayout_Leaf(
        nodeId: final nodeId,
        glyphs: final glyphs,
        width: final width,
        height: final height,
        depth: final depth,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_u_32(nodeId, serializer);
        sse_encode_list_math_node(glyphs, serializer);
        sse_encode_f_64(width, serializer);
        sse_encode_f_64(height, serializer);
        sse_encode_f_64(depth, serializer);
      case NodeLayout_Command(
        nodeId: final nodeId,
        kind: final kind,
        width: final width,
        height: final height,
        depth: final depth,
        childBlocks: final childBlocks,
        decorations: final decorations,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_u_32(nodeId, serializer);
        sse_encode_box_autoadd_command_layout_kind(kind, serializer);
        sse_encode_f_64(width, serializer);
        sse_encode_f_64(height, serializer);
        sse_encode_f_64(depth, serializer);
        sse_encode_list_block_layout(childBlocks, serializer);
        sse_encode_list_math_node(decorations, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_block_selection(
    BlockSelection? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_block_selection(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_path_command(PathCommand self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case PathCommand_MoveTo(x: final x, y: final y):
        sse_encode_i_32(0, serializer);
        sse_encode_f_64(x, serializer);
        sse_encode_f_64(y, serializer);
      case PathCommand_LineTo(x: final x, y: final y):
        sse_encode_i_32(1, serializer);
        sse_encode_f_64(x, serializer);
        sse_encode_f_64(y, serializer);
      case PathCommand_CubicTo(
        x1: final x1,
        y1: final y1,
        x2: final x2,
        y2: final y2,
        x: final x,
        y: final y,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_f_64(x1, serializer);
        sse_encode_f_64(y1, serializer);
        sse_encode_f_64(x2, serializer);
        sse_encode_f_64(y2, serializer);
        sse_encode_f_64(x, serializer);
        sse_encode_f_64(y, serializer);
      case PathCommand_QuadTo(
        x1: final x1,
        y1: final y1,
        x: final x,
        y: final y,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_f_64(x1, serializer);
        sse_encode_f_64(y1, serializer);
        sse_encode_f_64(x, serializer);
        sse_encode_f_64(y, serializer);
      case PathCommand_Close():
        sse_encode_i_32(4, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
