// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'node_kind.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Arena-based math tree. Blocks contain sequences of Nodes, Nodes contain
/// child Blocks. Mirrors MathQuill's doubly-linked tree structure.
class Arena {
  final List<Node> nodes;
  final List<Block> blocks;

  /// Root block (top-level expression).
  final BlockId root;

  const Arena({required this.nodes, required this.blocks, required this.root});

  @override
  int get hashCode => nodes.hashCode ^ blocks.hashCode ^ root.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Arena &&
          runtimeType == other.runtimeType &&
          nodes == other.nodes &&
          blocks == other.blocks &&
          root == other.root;
}

/// A block is a sequence of nodes. The cursor always lives in a block.
class Block {
  /// First child node (None if empty).
  final NodeId? first;

  /// Last child node (None if empty).
  final NodeId? last;

  /// Parent node that owns this block (None for root block).
  final NodeId? parent;

  const Block({this.first, this.last, this.parent});

  @override
  int get hashCode => first.hashCode ^ last.hashCode ^ parent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Block &&
          runtimeType == other.runtimeType &&
          first == other.first &&
          last == other.last &&
          parent == other.parent;
}

/// Index into `Arena::blocks`.
class BlockId {
  final int field0;

  const BlockId({required this.field0});

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockId &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

/// A node (command or symbol) in the math tree.
class Node {
  final NodeKind kind;

  /// Parent block this node lives in.
  final BlockId parent;

  /// Left sibling (None if first in block).
  final NodeId? left;

  /// Right sibling (None if last in block).
  final NodeId? right;

  /// Child blocks (e.g. frac has 2, sqrt has 1, symbol has 0).
  final List<BlockId> blocks;

  const Node({
    required this.kind,
    required this.parent,
    this.left,
    this.right,
    required this.blocks,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      parent.hashCode ^
      left.hashCode ^
      right.hashCode ^
      blocks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Node &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          parent == other.parent &&
          left == other.left &&
          right == other.right &&
          blocks == other.blocks;
}

/// Index into `Arena::nodes`.
class NodeId {
  final int field0;

  const NodeId({required this.field0});

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeId &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}
