// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'arena.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Position between nodes in a block. Equivalent to MathQuill's Point type.
class Cursor {
  /// The block the cursor is in.
  final BlockId parent;

  /// Node to the left of cursor (None = at start of block).
  final NodeId? left;

  /// Node to the right of cursor (None = at end of block).
  final NodeId? right;

  const Cursor({required this.parent, this.left, this.right});

  @override
  int get hashCode => parent.hashCode ^ left.hashCode ^ right.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cursor &&
          runtimeType == other.runtimeType &&
          parent == other.parent &&
          left == other.left &&
          right == other.right;
}

/// Represents a selected range of nodes. The anticursor is the anchor
/// and the main cursor is the focus (moving end).
class Selection {
  /// Where selection started (anchor).
  final Cursor anticursor;

  const Selection({required this.anticursor});

  @override
  int get hashCode => anticursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Selection &&
          runtimeType == other.runtimeType &&
          anticursor == other.anticursor;
}
