// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'node_kind.freezed.dart';

/// TeX atom families for spacing rules.
enum AtomFamily { ord, bin, rel, op, open, close, punct, inner }

@freezed
sealed class NodeKind with _$NodeKind {
  const NodeKind._();

  const factory NodeKind.symbol({
    required String text,
    required AtomFamily atomFamily,
  }) = NodeKind_Symbol;

  /// `\frac{numer}{denom}` — 2 blocks: [numer, denom]
  const factory NodeKind.frac() = NodeKind_Frac;

  /// `\sqrt{body}` — 1 block: [body]
  const factory NodeKind.sqrt() = NodeKind_Sqrt;

  /// `\sqrt[index]{body}` — 2 blocks: [index, body]
  const factory NodeKind.nthRoot() = NodeKind_NthRoot;

  /// `x^{sup}` — 1 block: [superscript]
  const factory NodeKind.sup() = NodeKind_Sup;

  /// `x_{sub}` — 1 block: [subscript]
  const factory NodeKind.sub() = NodeKind_Sub;

  /// `x^{sup}_{sub}` — 2 blocks: [sup, sub]
  const factory NodeKind.supSub() = NodeKind_SupSub;

  /// Accent above: `\hat`, `\bar`, `\vec`, etc. — 1 block: [body]
  const factory NodeKind.accent({required String label}) = NodeKind_Accent;

  /// `\overline{body}` — 1 block: [body]
  const factory NodeKind.overline() = NodeKind_Overline;

  /// `\underline{body}` — 1 block: [body]
  const factory NodeKind.underline() = NodeKind_Underline;

  /// `\left( ... \right)` — 1 block: [body]
  const factory NodeKind.leftRight({
    required String leftDelim,
    required String rightDelim,
  }) = NodeKind_LeftRight;

  /// Matrix/array — rows*cols blocks
  const factory NodeKind.matrix({required BigInt rows, required BigInt cols}) =
      NodeKind_Matrix;

  /// `\sum`, `\prod`, `\int`, `\lim`, etc. — 1-2 blocks: [below] or [below, above]
  const factory NodeKind.sumLike({required String ctrlSeq}) = NodeKind_SumLike;

  /// `\text{...}` — 1 block: [text content]
  const factory NodeKind.text() = NodeKind_Text;

  /// `\color{color}{body}` — 1 block: [body]
  const factory NodeKind.color(String field0) = NodeKind_Color;

  /// `\mathbf`, `\mathrm`, etc. — 1 block: [body]
  const factory NodeKind.font(String field0) = NodeKind_Font;

  /// `\scriptsize`, `\large`, etc. — 1 block: [body]
  const factory NodeKind.sizing(BigInt field0) = NodeKind_Sizing;

  /// `\phantom{body}` — 1 block: [body]
  const factory NodeKind.phantom() = NodeKind_Phantom;

  /// `\overbrace`, `\underbrace` — 1 block: [body]
  const factory NodeKind.horizBrace({
    required String label,
    required bool isOver,
  }) = NodeKind_HorizBrace;

  /// `\xleftarrow`, `\xrightarrow` — 1-2 blocks: [above] or [below, above]
  const factory NodeKind.xArrow({required String label}) = NodeKind_XArrow;

  /// `\operatorname{...}` — 1 block: [body]
  const factory NodeKind.operatorName() = NodeKind_OperatorName;

  /// Opaque LaTeX that we can't structurally edit.
  /// Rendered as a single unit, cursor skips over it.
  const factory NodeKind.raw(String field0) = NodeKind_Raw;
}
