// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'arena.dart';
import 'cursor.dart';
import 'node_kind.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Editor state: the arena tree, cursor position, and optional selection.
class State {
  final Arena arena;
  final Cursor cursor;
  final Selection? selection;

  const State({required this.arena, required this.cursor, this.selection});

  @override
  int get hashCode => arena.hashCode ^ cursor.hashCode ^ selection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is State &&
          runtimeType == other.runtimeType &&
          arena == other.arena &&
          cursor == other.cursor &&
          selection == other.selection;
}
