// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'math_api.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'editor_layout.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `build_block_layout`, `build_editor_layout`, `build_node_layout`, `build_readonly_layout`, `collect_subtree_glyphs`, `compute_baseline_shift`, `compute_block_selection`, `compute_cursor_index`, `compute_font_scale`, `compute_glyph_extents`, `compute_left_x`, `compute_right_x`, `from_state`, `glyphs_for_subtree`, `glyphs_for`, `new`, `none`, `patch_empty_child_blocks`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BlockCursorInfo`, `GlyphIndex`, `SelectionInfo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Layout for a single block (sequence of nodes).
class BlockLayout {
  final int blockId;
  final double width;
  final double height;
  final double depth;

  /// X-position (em) for each caret gap: index 0 = before first node, index n = after last.
  final Float64List caretPositions;

  /// Y-offset (em) of this block's leaf text baseline from the expression baseline.
  /// Numerator blocks have positive values (above), denominator negative (below).
  final double baselineShift;

  /// Effective font-size multiplier for leaf content in this block (1.0 for root, ~0.7 for fractions).
  final double fontScale;

  /// Leftmost x-coordinate (em) across all glyphs in this block's subtree.
  final double leftX;
  final List<NodeLayout> children;

  /// Caret position if cursor is in this block (index into children gaps: 0 = before first, n = after last).
  final int? cursorIndex;

  /// Selection range if active in this block.
  final BlockSelection? selection;

  /// Whether this block has no child nodes (empty placeholder).
  final bool isEmpty;

  const BlockLayout({
    required this.blockId,
    required this.width,
    required this.height,
    required this.depth,
    required this.caretPositions,
    required this.baselineShift,
    required this.fontScale,
    required this.leftX,
    required this.children,
    this.cursorIndex,
    this.selection,
    required this.isEmpty,
  });

  @override
  int get hashCode =>
      blockId.hashCode ^
      width.hashCode ^
      height.hashCode ^
      depth.hashCode ^
      caretPositions.hashCode ^
      baselineShift.hashCode ^
      fontScale.hashCode ^
      leftX.hashCode ^
      children.hashCode ^
      cursorIndex.hashCode ^
      selection.hashCode ^
      isEmpty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockLayout &&
          runtimeType == other.runtimeType &&
          blockId == other.blockId &&
          width == other.width &&
          height == other.height &&
          depth == other.depth &&
          caretPositions == other.caretPositions &&
          baselineShift == other.baselineShift &&
          fontScale == other.fontScale &&
          leftX == other.leftX &&
          children == other.children &&
          cursorIndex == other.cursorIndex &&
          selection == other.selection &&
          isEmpty == other.isEmpty;
}

/// Selection range within a block (indices into children gaps).
class BlockSelection {
  final int start;
  final int end;

  const BlockSelection({required this.start, required this.end});

  @override
  int get hashCode => start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockSelection &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end;
}

@freezed
sealed class CommandLayoutKind with _$CommandLayoutKind {
  const CommandLayoutKind._();

  const factory CommandLayoutKind.frac() = CommandLayoutKind_Frac;
  const factory CommandLayoutKind.sqrt() = CommandLayoutKind_Sqrt;
  const factory CommandLayoutKind.nthRoot() = CommandLayoutKind_NthRoot;
  const factory CommandLayoutKind.sup() = CommandLayoutKind_Sup;
  const factory CommandLayoutKind.sub() = CommandLayoutKind_Sub;
  const factory CommandLayoutKind.supSub() = CommandLayoutKind_SupSub;
  const factory CommandLayoutKind.overline() = CommandLayoutKind_Overline;
  const factory CommandLayoutKind.underline() = CommandLayoutKind_Underline;
  const factory CommandLayoutKind.leftRight() = CommandLayoutKind_LeftRight;
  const factory CommandLayoutKind.sumLike() = CommandLayoutKind_SumLike;
  const factory CommandLayoutKind.matrix({
    required int rows,
    required int cols,
  }) = CommandLayoutKind_Matrix;
  const factory CommandLayoutKind.text() = CommandLayoutKind_Text;

  /// Transient command input box: user is typing `\commandname`.
  const factory CommandLayoutKind.latexCommandInput({required String text}) =
      CommandLayoutKind_LatexCommandInput;
  const factory CommandLayoutKind.other() = CommandLayoutKind_Other;
}

/// Tree-structured layout output for the widget tree renderer.
class EditorLayout {
  final BlockLayout root;

  /// Decoration nodes (fraction bars, radical signs, delimiters) that have no
  /// arena node_id. These are generated by katex-rs's layout engine and must
  /// be painted alongside the tree's glyphs.
  final List<MathNode> untagged;

  const EditorLayout({required this.root, required this.untagged});

  @override
  int get hashCode => root.hashCode ^ untagged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorLayout &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          untagged == other.untagged;
}

@freezed
sealed class NodeLayout with _$NodeLayout {
  const NodeLayout._();

  /// A leaf node (symbol) — carries its rendered glyphs.
  const factory NodeLayout.leaf({
    required int nodeId,
    required List<MathNode> glyphs,
    required double width,
    required double height,
    required double depth,

    /// Leftmost x-coordinate (em) of this node's glyphs.
    required double leftX,
  }) = NodeLayout_Leaf;

  /// A command node (frac, sqrt, etc.) — carries child blocks and decorations.
  const factory NodeLayout.command({
    required int nodeId,
    required CommandLayoutKind kind,
    required double width,
    required double height,
    required double depth,

    /// Leftmost x-coordinate (em) of this node's glyphs.
    required double leftX,
    required List<BlockLayout> childBlocks,
    required List<MathNode> decorations,
  }) = NodeLayout_Command;
}
