// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'math_api.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'editor_layout.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `build_block_layout`, `build_editor_layout`, `build_node_layout`, `build_readonly_layout`, `collect_subtree_glyphs`, `compute_block_selection`, `compute_cursor_index`, `compute_glyph_extents`, `from_state`, `glyphs_for_subtree`, `glyphs_for`, `new`, `none`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BlockCursorInfo`, `GlyphIndex`, `SelectionInfo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Layout for a single block (sequence of nodes).
class BlockLayout {
  final int blockId;
  final double width;
  final double height;
  final double depth;
  final List<NodeLayout> children;

  /// Caret position if cursor is in this block (index into children gaps: 0 = before first, n = after last).
  final int? cursorIndex;

  /// Selection range if active in this block.
  final BlockSelection? selection;

  const BlockLayout({
    required this.blockId,
    required this.width,
    required this.height,
    required this.depth,
    required this.children,
    this.cursorIndex,
    this.selection,
  });

  @override
  int get hashCode =>
      blockId.hashCode ^
      width.hashCode ^
      height.hashCode ^
      depth.hashCode ^
      children.hashCode ^
      cursorIndex.hashCode ^
      selection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockLayout &&
          runtimeType == other.runtimeType &&
          blockId == other.blockId &&
          width == other.width &&
          height == other.height &&
          depth == other.depth &&
          children == other.children &&
          cursorIndex == other.cursorIndex &&
          selection == other.selection;
}

/// Selection range within a block (indices into children gaps).
class BlockSelection {
  final int start;
  final int end;

  const BlockSelection({required this.start, required this.end});

  @override
  int get hashCode => start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockSelection &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end;
}

@freezed
sealed class CommandLayoutKind with _$CommandLayoutKind {
  const CommandLayoutKind._();

  const factory CommandLayoutKind.frac() = CommandLayoutKind_Frac;
  const factory CommandLayoutKind.sqrt() = CommandLayoutKind_Sqrt;
  const factory CommandLayoutKind.nthRoot() = CommandLayoutKind_NthRoot;
  const factory CommandLayoutKind.sup() = CommandLayoutKind_Sup;
  const factory CommandLayoutKind.sub() = CommandLayoutKind_Sub;
  const factory CommandLayoutKind.supSub() = CommandLayoutKind_SupSub;
  const factory CommandLayoutKind.overline() = CommandLayoutKind_Overline;
  const factory CommandLayoutKind.underline() = CommandLayoutKind_Underline;
  const factory CommandLayoutKind.leftRight() = CommandLayoutKind_LeftRight;
  const factory CommandLayoutKind.sumLike() = CommandLayoutKind_SumLike;
  const factory CommandLayoutKind.matrix({
    required int rows,
    required int cols,
  }) = CommandLayoutKind_Matrix;
  const factory CommandLayoutKind.text() = CommandLayoutKind_Text;
  const factory CommandLayoutKind.other() = CommandLayoutKind_Other;
}

/// Tree-structured layout output for the widget tree renderer.
class EditorLayout {
  final BlockLayout root;

  /// Decoration nodes (fraction bars, radical signs, delimiters) that have no
  /// arena node_id. These are generated by katex-rs's layout engine and must
  /// be painted alongside the tree's glyphs.
  final List<MathNode> untagged;

  const EditorLayout({required this.root, required this.untagged});

  @override
  int get hashCode => root.hashCode ^ untagged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorLayout &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          untagged == other.untagged;
}

@freezed
sealed class NodeLayout with _$NodeLayout {
  const NodeLayout._();

  /// A leaf node (symbol) — carries its rendered glyphs.
  const factory NodeLayout.leaf({
    required int nodeId,
    required List<MathNode> glyphs,
    required double width,
    required double height,
    required double depth,
  }) = NodeLayout_Leaf;

  /// A command node (frac, sqrt, etc.) — carries child blocks and decorations.
  const factory NodeLayout.command({
    required int nodeId,
    required CommandLayoutKind kind,
    required double width,
    required double height,
    required double depth,
    required List<BlockLayout> childBlocks,
    required List<MathNode> decorations,
  }) = NodeLayout_Command;
}
