// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'editor_layout.dart';
import 'math_api.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'editor_api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `build_snapshot`, `collect_leaf_ids`, `collect_leaves_in_block`, `convert_intent`, `empty_snapshot`, `next_id`, `resolve_tap_block`, `with_registry`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EditorEntry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Create a new empty math editor. Returns an editor ID.
String createEditor() => RustLib.instance.api.crateApiEditorApiCreateEditor();

/// Create a math editor pre-populated with LaTeX. Returns an editor ID.
String createEditorFromLatex({required String latex}) =>
    RustLib.instance.api.crateApiEditorApiCreateEditorFromLatex(latex: latex);

/// Dispatch an intent and get back the new snapshot.
EditorSnapshot dispatchEditor({
  required String id,
  required EditorIntent intent,
  required bool displayMode,
}) => RustLib.instance.api.crateApiEditorApiDispatchEditor(
  id: id,
  intent: intent,
  displayMode: displayMode,
);

/// Get the current snapshot without dispatching.
EditorSnapshot getEditorSnapshot({
  required String id,
  required bool displayMode,
}) => RustLib.instance.api.crateApiEditorApiGetEditorSnapshot(
  id: id,
  displayMode: displayMode,
);

/// Close and dispose an editor.
void closeEditor({required String id}) =>
    RustLib.instance.api.crateApiEditorApiCloseEditor(id: id);

@freezed
sealed class EditorIntent with _$EditorIntent {
  const EditorIntent._();

  const factory EditorIntent.insertSymbol({required String ch}) =
      EditorIntent_InsertSymbol;
  const factory EditorIntent.insertFrac() = EditorIntent_InsertFrac;
  const factory EditorIntent.insertSqrt() = EditorIntent_InsertSqrt;
  const factory EditorIntent.insertNthRoot() = EditorIntent_InsertNthRoot;
  const factory EditorIntent.insertSup() = EditorIntent_InsertSup;
  const factory EditorIntent.insertSub() = EditorIntent_InsertSub;
  const factory EditorIntent.insertParentheses() =
      EditorIntent_InsertParentheses;
  const factory EditorIntent.insertBrackets() = EditorIntent_InsertBrackets;
  const factory EditorIntent.insertBraces() = EditorIntent_InsertBraces;
  const factory EditorIntent.insertAbs() = EditorIntent_InsertAbs;
  const factory EditorIntent.insertSum() = EditorIntent_InsertSum;
  const factory EditorIntent.insertProduct() = EditorIntent_InsertProduct;
  const factory EditorIntent.insertIntegral() = EditorIntent_InsertIntegral;
  const factory EditorIntent.insertLimit() = EditorIntent_InsertLimit;
  const factory EditorIntent.insertOverline() = EditorIntent_InsertOverline;
  const factory EditorIntent.insertUnderline() = EditorIntent_InsertUnderline;
  const factory EditorIntent.insertText() = EditorIntent_InsertText;

  /// Begin command input mode: insert LatexCommandInput node.
  const factory EditorIntent.insertCommandInput() =
      EditorIntent_InsertCommandInput;

  /// Append a character to the active command input.
  const factory EditorIntent.commandInputType({required String ch}) =
      EditorIntent_CommandInputType;

  /// Remove last character from command input, or remove it if empty.
  const factory EditorIntent.commandInputBackspace() =
      EditorIntent_CommandInputBackspace;

  /// Resolve the active command input (extract name, insert command/symbol).
  const factory EditorIntent.resolveCommandInput() =
      EditorIntent_ResolveCommandInput;

  /// Cancel command input mode (remove the node).
  const factory EditorIntent.cancelCommandInput() =
      EditorIntent_CancelCommandInput;
  const factory EditorIntent.moveLeft() = EditorIntent_MoveLeft;
  const factory EditorIntent.moveRight() = EditorIntent_MoveRight;

  /// Space key: exit current block to the right (MathQuill-style).
  const factory EditorIntent.escapeRight() = EditorIntent_EscapeRight;
  const factory EditorIntent.moveUp() = EditorIntent_MoveUp;
  const factory EditorIntent.moveDown() = EditorIntent_MoveDown;
  const factory EditorIntent.moveToStart() = EditorIntent_MoveToStart;
  const factory EditorIntent.moveToEnd() = EditorIntent_MoveToEnd;
  const factory EditorIntent.selectLeft() = EditorIntent_SelectLeft;
  const factory EditorIntent.selectRight() = EditorIntent_SelectRight;
  const factory EditorIntent.selectAll() = EditorIntent_SelectAll;
  const factory EditorIntent.deleteBackward() = EditorIntent_DeleteBackward;
  const factory EditorIntent.deleteForward() = EditorIntent_DeleteForward;
  const factory EditorIntent.setLatex({required String latex}) =
      EditorIntent_SetLatex;
  const factory EditorIntent.tapBlock({
    required int blockId,
    required int caretIndex,
  }) = EditorIntent_TapBlock;
}

/// Snapshot of the editor state, returned after every dispatch.
class EditorSnapshot {
  /// Hierarchical layout tree for widget-tree rendering.
  final EditorLayout editorLayout;

  /// Current LaTeX string.
  final String latex;

  /// Whether the cursor is in command input mode (inside a LatexCommandInput node).
  final bool inCommandInput;

  const EditorSnapshot({
    required this.editorLayout,
    required this.latex,
    required this.inCommandInput,
  });

  @override
  int get hashCode =>
      editorLayout.hashCode ^ latex.hashCode ^ inCommandInput.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditorSnapshot &&
          runtimeType == other.runtimeType &&
          editorLayout == other.editorLayout &&
          latex == other.latex &&
          inCommandInput == other.inCommandInput;
}
