// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'editor_layout.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'math_api.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// Layout a LaTeX expression, returning positioned nodes for rendering.
///
/// All coordinates in the returned [`MathLayout`] are in **em** units.
/// Multiply by the desired font size in logical pixels to get pixel coords.
///
/// Returns an empty layout on parse error.
MathLayout layoutMath({required String latex, required bool displayMode}) =>
    RustLib.instance.api.crateApiMathApiLayoutMath(
      latex: latex,
      displayMode: displayMode,
    );

/// Layout a LaTeX expression as a hierarchical tree for widget-tree rendering.
///
/// Creates a temporary Arena via `import_latex`, builds the layout, and returns
/// a tree without cursor/selection. No editor registry involved.
///
/// This is used for `MathView(selectable: true)`.
EditorLayout layoutMathTree({
  required String latex,
  required bool displayMode,
}) => RustLib.instance.api.crateApiMathApiLayoutMathTree(
  latex: latex,
  displayMode: displayMode,
);

/// Positioned math layout, ready for rendering.
/// All dimensions are in **em** units — multiply by font size in pixels for px coords.
class MathLayout {
  /// Total width in em.
  final double width;

  /// Ascent above the baseline in em.
  final double height;

  /// Descent below the baseline in em.
  final double depth;

  /// Positioned rendering nodes.
  final List<MathNode> nodes;

  const MathLayout({
    required this.width,
    required this.height,
    required this.depth,
    required this.nodes,
  });

  @override
  int get hashCode =>
      width.hashCode ^ height.hashCode ^ depth.hashCode ^ nodes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MathLayout &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          depth == other.depth &&
          nodes == other.nodes;
}

@freezed
sealed class MathNode with _$MathNode {
  const MathNode._();

  /// A text glyph — render with a KaTeX font at `(x, y)`.
  const factory MathNode.glyph({
    required int codepoint,
    required double x,
    required double y,
    required String fontName,
    required double scale,

    /// Advance width in em (actual glyph width from font metrics, scaled).
    required double width,
    String? color,

    /// Optional opaque ID for correlating with a source tree (e.g. editor arena).
    int? nodeId,
  }) = MathNode_Glyph;

  /// Fraction bar, overline, underline, etc.
  const factory MathNode.rule({
    required double x,
    required double y,
    required double width,
    required double height,
    String? color,

    /// Optional opaque ID for correlating with a source tree.
    int? nodeId,
  }) = MathNode_Rule;

  /// Stretchy SVG element (radical sign, large delimiters, wide accents).
  /// Path commands are pre-parsed — build a canvas Path directly from these.
  const factory MathNode.svgPath({
    required double x,
    required double y,
    required double width,
    required double height,
    required double viewBoxX,
    required double viewBoxY,
    required double viewBoxWidth,
    required double viewBoxHeight,
    required List<PathCommand> commands,

    /// Optional opaque ID for correlating with a source tree.
    int? nodeId,
  }) = MathNode_SvgPath;
}

@freezed
sealed class PathCommand with _$PathCommand {
  const PathCommand._();

  /// Move to (x, y).
  const factory PathCommand.moveTo({required double x, required double y}) =
      PathCommand_MoveTo;

  /// Line to (x, y).
  const factory PathCommand.lineTo({required double x, required double y}) =
      PathCommand_LineTo;

  /// Cubic Bézier to (x, y) with control points (x1, y1) and (x2, y2).
  const factory PathCommand.cubicTo({
    required double x1,
    required double y1,
    required double x2,
    required double y2,
    required double x,
    required double y,
  }) = PathCommand_CubicTo;

  /// Quadratic Bézier to (x, y) with control point (x1, y1).
  const factory PathCommand.quadTo({
    required double x1,
    required double y1,
    required double x,
    required double y,
  }) = PathCommand_QuadTo;

  /// Close the current sub-path.
  const factory PathCommand.close() = PathCommand_Close;
}
